config/routes.rb
Rails.application.routes.draw do
   

  get 'payments/index'

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  #before sidekiq
  #devise_for :users
  # sidekiq
  devise_for :users, controllers: { registrations: "users/registrations"}
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  
  #root :to => "statics#index"
  #Example of regular route:
  #get 'about' => 'pages#about', as: 'about'
  #get '/about' => 'statics#about', :as => :about
  get 'about' => 'about#index', as: 'about'
  get 'settings/index'
  #get 'movies/index_search' => 'movies#index_search'
  #Example resource route
  resources :peliculas do
    resources :comentarios 
  end
  
  resources :settings
  resources :charges
  resources :select_movies, only: :index
  resources :payments, only: :index
  #root 'peliculas#index', as: 'home'
  #added for method root_path (search)
  root :to => "statics#index"

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_boxsearchs.html.erb
<style>
.boxsearchs {background-color:#0B610B;padding:5px;height:44px;font-size: 12px; border-top: 2px solid #173B0B;}
.colorselect {
    linear-gradient(45deg, transparent 50%, blue 50%),
    linear-gradient(135deg, blue 50%, transparent 50%),
    linear-gradient(to right, skyblue, skyblue);
}
 /* SMARTHPHONE */
@media (max-width: 590px) { 
  .boxsearchs {height:130px;}
  .input-group { margin: 0.4% 5%;}
}  
/* TABLET */
@media (max-width: 991px) {
   
}
</style>
<div class="row">
  <div class="boxsearchs"> 
    <!-- BUSQUEDA POR NAME DE PELICULA --> 
    <div class="col-sm-3 col-xs-12" style="text-align:center;"> 
      <%= form_tag(root_path, :method => "get", html: { class: 'form-inline'} ) do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control",  :placeholder => "Buscar por Pelicula" %>
            <span class="input-group-btn">
              <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                <i class="fa fa-search"></i>
              <%end%>  
            </span>
        </div>
      <%end%>
    </div><!-- end col-sm-3 -->
    <!-- BUSQUEDA POR AÑO DE LA PELICULA --> 
    <div class="col-sm-3 col-xs-12" style="text-align:center;">
      <%= form_tag(root_path, :method => "get", html: { class: 'form-inline'} ) do %>
        <div class="input-group">
          <%= text_field_tag :search_year, params[:search_year], class: "form-control",  :placeholder => "Buscar por Año" %>
            <span class="input-group-btn">
              <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                <i class="fa fa-search"></i>
              <%end%>  
            </span>
        </div>
      <%end%>
    </div> <!-- end col-sm-3 -->   
    <!-- BUSQUEDA POR EL GENERO EN UN DROPDOWN SELECT DE PELICULA --> 
    <div class="col-sm-6 col-xs-12">
        <%= form_tag(root_path, :method => "get", id: "genre") do %> 
          <%= select_tag :search_genre, ("<option>&#xf015; Seleccionar Genero</option><br><option>ALL</option><option>ACTION</option><option>ADVENTURE</option><option>ANIME</option><option>COMEDY</option><option>CRIME</option><option>DRAMA</option><option>HISTORICAL</option><option>HORROR</option><option>MUSICALS</option><option>SCIENCE-FICTION</option><option>WAR</option><option>WESTERNS</option>").html_safe, class: 'form-control colorselect pull-right', style:"width:235px; margin-right:5%; font-family: sans-serif, 'FontAwesome';", :onchange => "this.form.submit()"%> 
        <%end%> 
    </div> <!-- end col-sm-6 --> 
  </div> <!-- end row -->
</div> <!-- end -->

app/views/shared/_flash_messages.html.erb
<div class="row">
  <div class="col-sm-12">
    <% flash.each do |type, message| %>
      <% unless message.blank? %>
        <div id="flashmensaje" class="alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message.html_safe %>
        </div>
      <%end%>
    <%end%>
  </div><!-- col-sm-12 --> 
</div><!-- end row -->
<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
      $('#flashmensaje').remove();
    }, 5000);
  })
</script>

app/views/shared/_footer.html.erb
<div class="estilosapp2">
	<footer id="footer">
		<div class="row">
			<div class="container">
			<div class="col-sm-4 col-xs-6 relleno size12">
  				<a href="">Help</a> </br>
  				<a href="">About Movies Today</a> </br>
  				<a href="">What's the Movies Today</a> </br>
  				<a href="">Jobs</a> </br>
  				<a href="">Advertise</a> </br>
			</div><!-- col-sm-3 -->
			<div class="col-sm-4 col-xs-6 relleno size12">
  				<a href="">Critic Submission</a> </br>
  				<a href="">API</a> </br>
  				<a href="">Licensing</a> </br>
			</div>  <!-- col-sm-3 -->
			<div class="col-sm-4 col-xs-12 relleno">
 				<p class="white size18"><b>FOLLOW US</b></p>
 				<a class="fa fa-2x fa-twitter margin10le" href="" title="Twitter"></a>
 				<a class="fa fa-2x fa-facebook-square margin10le" href="" title="Facebook"></a>
 				<a class="fa fa-2x fa-google-plus margin10le" href="" title="Google Plus"></a>
 				<a class="fa fa-2x fa-youtube-play margin10le" href="" title="Youtube"></a>
 				<a class="fa fa-2x fa-tumblr margin10le" href="" title="Tumblr"></a>
			</div><!-- col-sm-3 -->
		</div><!-- container --> 		
		</div><!-- row --> 
	</footer>  
</div><!-- end estilosapp2 -->

app/views/shared/_header.html.erb
<style>
/* SMARTHPHONE */
@media (max-width: 580px) { 
  .navbar {color: black !important;}
  .navbar-brand {margin-top:-46px !important;}
  .collapse {background-color: grey !important; color: black !important;}
  .dropdown-menu li { margin-left: 40px !important;color: black !important;}
  .dropdown-header {color: black !important;}
  .dropdown-toggle, .dropdown .open {color: black !important;}
  .nav > li > a  {color: white !important;}
  .navbar-right {float:left; margin-top: 30px !important;}
}  
/* TABLET */
@media (max-width: 991px) {
  .navbar-right {margin-top:-55px; margin-right: -120px;}
}
  .row--intro {
    padding-top: 20px;
    font-size: 16px;
    line-height: 28px;
    font-weight: 300;
    color: #fff;
    opacity: 0.4;
  }
  .row--intro span {
    font-size: 11px;
  }
  .skew-title {
    font-size: 25px;
    margin-top:16px;
    margin-left: -50px !important;
    margin-right: 5px;
  }
  .skew-title span {
    position: relative;
    display: inline-block;
    width: 40px;
    height: 50px;
    margin: auto;
    z-index: 2;
    text-align: center;
    color: #fff;
    font-family: 'roboto condensed';
    font-weight: 700;
    font-size: 35.714285714285715px;
    line-height: 50px;
    -webkit-transform: skewY(-15deg);
    transform: skewY(-15deg);
    -webkit-transform-origin: 0 100%;
    transform-origin: 0 100%;
    -webkit-transition: all 0.2s;
    transition: all 0.2s;
    cursor: default;
  }
  .skew-title span:after,
  .skew-title span:before {
    display: block;
    top: 0;
    left: 0;
    width: 40px;
    height: 50px;
    position: absolute;
    background: #185a81;
    content: ' ';
    z-index: -1;
    -webkit-transition: all 0.2s;
    transition: all 0.2s;
  }
  .skew-title span:before {
    background: rgba(0,0,0,0.1);
    -webkit-transform: skewY(15deg);
            transform: skewY(15deg);
    -webkit-transform-origin: 0 0;
            transform-origin: 0 0;
  }
  .skew-title span:nth-child(even) {
    background-color: #144c6e;
    -webkit-transform: skewY(15deg);
            transform: skewY(15deg);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
    color: #d9d9d9;
  }
  .skew-title span:nth-child(even):after {
    background-color: #144c6e;
  }
  .skew-title span:nth-child(even):before {
    -webkit-transform-origin: 100% 0;
            transform-origin: 100% 0;
    -webkit-transform: skewY(-15deg);
            transform: skewY(-15deg);
  }
  .skew-title span.flat {
    -webkit-transform: skewY(0);
            transform: skewY(0);
    color: #fff;
  }
  .skew-title span.flat:before {
    -webkit-transform: skewY(0);
            transform: skewY(0);
  }
  .skew-title span.flat:nth-child(even):after {
    background-color: #185a81;
  }
  .skew-title span.alt:after {
    background-color: #b94a2c;
  }
  .skew-title span.alt:nth-child(even):after {
    background-color: #9d3f25;
  }
  .skew-title span.alt.flat:nth-child(even):after {
    background-color: #b94a2c;
  }
  .navbar-brand {
    width:100%;
    margin-left: 20px;
    margin-right: 25px;
  } 
  .estilosapp2 { font-size: 14px; }
</style> 
<div class="estilosapp2">
  <div class="row">
    <!-- NAVBAR BEGIN  -->
    <nav id="logo" class="navbar navbar-fixed navbar-default" role="navigation" style="margin-bottom:-1px; border-bottom: 2px solid #173B0B;"> 
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- BRAND -->
          <%= link_to root_path, class: "navbar-brand" do %>
            <span class="row skew-title">  
              <span>M</span><span>O</span><span>V</span><span>I</span><span>E</span><span class="last">S</span>
              <span class="alt">T</span><span class="alt">O</span><span class="alt">D</span><span class="alt">A</span><span class="alt last">Y</span>
            </span> 
          <%end%>  
          <script>
            (function() {
            $('.skew-title').children('span').hover((function() {
              var $el, n;
              $el = $(this);
              n = $el.index() + 1;
              $el.addClass('flat');
              if (n % 2 === 0) {
                return $el.prev().addClass('flat');
              } else {
                if (!$el.hasClass('last')) {
                  return $el.next().addClass('flat');
                }
              }
            }), function() {
              return $('.flat').removeClass('flat');
            });
          }).call(this);
        </script>
        </div><!-- navbar-header -->
        <div class="container">
          <!-- NAVBAR DROPDOWNS-->
          <div class="collapse navbar-collapse" id="navbar-collapsable" style="margin-top:41px;">
            <ul class="nav navbar-nav foo" id="menu" >
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">MOVIES & DVDs<b class="caret"></b></a>
                <ul class="dropdown-menu" style="padding: 20px; ">
                  <li class="dropdown-header bgreen">MOVIES & DVDs</li>
                  <b class="caret"></b>
                  <li><%= link_to 'Peliculas', peliculas_path %></li>
                  <li></li>
                  <li><%= link_to 'About', about_path %></li>
                  <li class="divider"></li>
                  <li><a href="/admin">Admin Dashboard</a></li>
                  <li><a href="#">Help</a></li>
                </ul>
              </li><!-- end dropdown -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">TV<b class="caret"></b></a>
                <ul class="dropdown-menu" style="padding: 20px; ">
                  <li class="dropdown-header bgreen">TV</li>
                  <b class="caret"></b>
                  <li><a href="/one">One</a></li>
                  <li><a href="/two">Two</a></li>
                  <li><a href="/three">Three</a></li>
                  <li class="divider"></li>
                  <li><a href="/admin">Admin Dashboard</a></li>
                  <li><a href="/admin/users">Users</a></li>
                </ul>
              </li><!-- end dropdown -->
              <li><%= link_to "Nosotros", about_path, style:"float:left; color:white" %></li> 
            </ul><!-- end nav navbar-nav -->
            <ul class="nav navbar-nav navbar-right"> 
                <% if user_signed_in? %> 
                  <li class="dropdown"> 
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a> 
                    <ul class="dropdown-menu" style="padding: 20px;">
                      <li class="dropdown-header bgreen">PROFILE</li>
                      <li><%= link_to '<i class="fa fa-address-book"></i>&nbsp;Settings'.html_safe, settings_path, class:"btn btn-primary size13 white nodecor", style:"margin-top: 15px; margin-bottom: 5px;" %></li>   
                      <li><%= link_to '<i class="fa fa-sign-out fa-3"></i>&nbsp;Sign Out'.html_safe, destroy_user_session_path, method: :delete, class:"btn btn-danger size13 white nodecor" %></li>   
                    </ul> 
                  </li><!-- end dropdown --> 
                <%else%> 
                  <li><%=link_to "Login", new_user_session_path, style:"color:white" %> </li>
                  <li><%=link_to "Sign up", new_user_registration_path, style:"color:white" %> </li> 
                <%end%> 
            </ul><!-- end nav navbar-nav -->
          </div><!-- collapse navbar-collapse -->
      </div><!-- end container -->
    </nav><!-- end nav --> 
  </div><!-- end estilosapp2 -->  
</div> <!-- end row -->