config/routes.rb
Rails.application.routes.draw do
   

  get 'payments/index'

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  #before sidekiq
  #devise_for :users
  # sidekiq
  devise_for :users, controllers: { registrations: "users/registrations"}
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  
  #root :to => "statics#index"
  #Example of regular route:
  #get 'about' => 'pages#about', as: 'about'
  #get '/about' => 'statics#about', :as => :about
  get 'about' => 'about#index', as: 'about'
  get 'settings/index'
  #get 'movies/index_search' => 'movies#index_search'
  #Example resource route
  resources :peliculas do
    resources :comentarios 
  end
  
  resources :settings
  resources :charges
  resources :select_movies, only: :index
  resources :payments, only: :index
  #root 'peliculas#index', as: 'home'
  #added for method root_path (search)
  root :to => "statics#index"

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
 
  has_many :comentarios, dependent: :destroy
  validates :director, presence: true, uniqueness: {message: "El nombre del Director ha de ser unico"}
	
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :stars, :inclusion => 0..10
	validates :stars, :numericality => {only_integer: true}
	validates :year, :numericality =>  {only_integer: true}
	validates :genre, presence: true
	validates :url, presence: true

	self.per_page = 8

def self.search(search)
  where("name like ?", "%" + "%#{search}%" + "%")
end

def self.search_year(search_year)
  where(year: search_year)
end


def self.search_genre(search_genre)
  where(genre: search_genre)
end
 

end
 

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
  	#@peliculas = Pelicula.all
    @peliculas = Pelicula.order("#{sort_column} #{sort_direction}")
  end
  def show
  	@pelicula = Pelicula.find(params[:id]) 
  end 
  def new
    @pelicula = Pelicula.new  
  end
  def create
    @pelicula = Pelicula.new(pelicula_params)
    if @pelicula.save 
      flash[:danger] = t('flash.message2')
      redirect_to peliculas_path
    else
      render 'new'
    end
  end
  def edit
    @pelicula = Pelicula.find(params[:id])
  end
  def update
    @pelicula = Pelicula.find(params[:id])
    if @pelicula.update_attributes(pelicula_params)
      redirect_to peliculas_path
    else
      render :edit
    end
  end
  def destroy
     @pelicula = Pelicula.find(params[:id])
     @pelicula.destroy
     redirect_to peliculas_path
  end
  private
  def pelicula_params
    params.require(:pelicula).permit(:name, :director, :actor, :email_contact,
    :oscar, :category, :stars, :country, :year, :revenue_amount, :url, :genre, :precio, :movie_main)
  end  
  def sortable_columns
    ["id","name","actor","year"]
  end
  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "id"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
 def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-triangle-top" : "glyphicon glyphicon-triangle-bottom"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}, class: "nodecor", title: "Column Sortable"
  end
end

app/views/peliculas/edit.html.erb
<style>
.field {margin-top: 10px;}
</style>
<div class="estilosapp2">
    <!-- PARCIAL HEADER --> 
    <%= render "shared/header" %>
    <div class="container"> 
        <div class="controladorej2">
            <div class="box">
                <div class="alert"><i class="fa fa-th-large fa-1x color-blue"></i>&nbsp;Editar Pelicula</div> 
                <%= form_for(@pelicula) do |f| %>
                    <div class="field">
                        <%= f.text_field :name, placeholder: "Nombre", class:"form-control" %>
                    </div> 
                    <div class="field">
                        <%= f.text_field :director, placeholder: "Director", class:"form-control" %>
                    </div> 
                    <div class="field">
                        <%= f.text_field :actor, placeholder: "Actor", class:"form-control" %>
                    </div> 
                    <div class="field">
                        <%= f.text_field :email_contact, placeholder: "Email", class:"form-control" %>
                    </div>  
                    <div class="field">
                        <%= f.text_field :stars, placeholder: "Stars", class:"form-control" %>
                    </div> 
                    <div class="field">
                       <%= f.select :country, options_for_country, :prompt => 'Seleccionar el Pais', class:'form-control' %>
                    </div>   
                    <div class="field">
                        <%= f.text_field :year, placeholder: "Año", class:"form-control" %>
                    </div>     
                    <div class="field">
                       <%= f.select :genre, options_for_genre, :prompt => 'Seleccionar el genero', class:'form-control' %>
                    </div>  
                    <div class="field">
                        <%= f.text_field :precio, placeholder: "Precio", class:"form-control" %>
                    </div>      
                    <div class="field">
                        <%= f.text_field :url, placeholder: "URL Imagen", class:"form-control" %>
                    </div>      
                     <div class="field">
                        <%= f.text_field :movie_main, placeholder: "Video Principal Cabecera Sintaxis Link = https://www.youtube.com/embed/LINK_YOUTUBE", class:"form-control" %>
                    </div>  
                    <div class="field">
                        <%= f.submit "Guardar", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
                    </div>
                <%end%>
                <%= link_to 'Listado de Peliculas', @pelicula, class:"btn btn-sm btn-primary nodecor", style:"margin-top: 15px;" %> 
                <br></br> 
                <ol>
                    <li>El nombre no puede estar vacio.</li>
                    <li>No permite guardar 2 nombres en la BD con el mismo nombre.</li>
                    <li>El apellido no puede estar vacio.</li>
                    <li>El email no puede estar vacio.</li>
                    <li>El email tiene que tener el formato standard con el signo @</li>
                </ol>  
                <hr/>
                <div class="margin20">
                    <%= @pelicula.errors.full_messages.each do |message| %>
                        <div class="message be-red white top-space text-center">
                            * <%= message %>
                        </div>
                    <%end%>
                </div> <!-- end margin20 -->    
            </div> <!-- end box -->
        </div> <!-- end controladorej2 -->
    </div> <!-- end container -->
</div> <!-- end estilosapp2 -->
<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>

app/views/peliculas/index.html.erb
<style>
.imagenthumb {width: 120px !important; height:120px !important;}
</style>
  <!-- PARCIAL HEADER --> 
  <%= render "shared/header" %>
  <div class="container"> 
    <div class="controladorej2">
      <% if user_signed_in? %> 
        <div class="boxp">
          <div class="alert bold size18"><i class="fa fa-home fa-1x color-teal"></i>&nbsp;MOVIES OPENING THIS WEEK</div>  
            <table class="table table-hover table-striped" border="0">
              <tbody>
                <th class="success"><%= sort_link "id" %></th>                       
                <th class="success" style="text-align: center;">Image</th>     
                <th class="success" style="text-align: center;">Stars</th>      
                <th class="success"><%= sort_link "name" %></th>      
                <th class="success"><%= sort_link "actor" %></th>     
                <th class="success"><%= sort_link "year" %></th>   
                <th class="success"></th>
              </tbody> 
              <% @peliculas.each do |peli| %>
                <tr>
                  <td style="vertical-align:middle;" align="center"><%= peli.id %></td>
                  <td style="vertical-align:middle;" align="center"><%= image_tag peli.url, class: "img-responsive imagenthumb" %></td>
                  <td style="vertical-align:middle;" align="center">
                    <%$i=0%>
                    <%while $i < peli.stars do%>
                      <span class="fa fa-star blue" title="<%= peli.stars %>" style="font-size: 17px;text-shadow:1px 2px 3px grey;"></span>
                      <% $i+=1 %>
                    <%end%>
                  </td>
                  <td style="vertical-align:middle;"><%= peli.name %></td>
                  <td style="vertical-align:middle;"><%= peli.actor %></td>
                  <td style="vertical-align:middle;"><%= peli.year %></td>
                  <td align="center" style="width:160px;vertical-align:middle;">
                    <%= link_to '', pelicula_path(peli), :title => "Visualizar", :class => 'btn btn-sm btn-success fa fa-1x fa-search nodecor', style:"color: white;" %>
                    <%= link_to '', edit_pelicula_path(peli), :title => "Editar", :class => 'btn btn-sm btn-primary fa fa-1x fa-edit nodecor', style:"color: white;" %>
                    <%= link_to '', { action: :destroy, id: peli.id }, method: :delete, :title => "Eliminar",:class => 'btn btn-sm btn-danger fa fa-1x fa-close nodecor', style:"color: white;" %>
                  </td>
                </tr>
              <%end%>
            </table>
            <%= link_to 'Nueva Pelicula', new_pelicula_path, title:"Añade una nueva pelicula !!", class:"btn btn-sm btn-danger nodecor" %>
        </div> <!-- end box -->     
      <%else%>
        <hr style="margin-top:30px;"/>
        <h3>Only for registered users. Solo para los usuarios registrados!!</h3>
        <hr style="margin-bottom:400px;"/>
      <%end%>
    </div> <!-- end controladorej2 -->
  </div> <!-- end container -->
</div> <!-- end estilosapp2 -->
<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>

app/views/peliculas/new.html.erb
<style>
.field {margin-top: 10px;}
</style>
<div class="estilosapp2">
    <!-- PARCIAL HEADER --> 
    <%= render "shared/header" %>
    <div class="container"> 
        <div class="controladorej2">
            <div class="box">
                <div class="alert"><i class="fa fa-th-large fa-1x color-blue"></i>&nbsp;Crear Pelicula</div> 
                    <%= form_for(@pelicula) do |f| %>
                        <div class="field">
                            <%= f.text_field :name, placeholder: "Nombre", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :director, placeholder: "Director", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :actor, placeholder: "Actor", class:"form-control" %>
                        </div>  
                        <div class="field">
                            <%= f.text_field :email_contact, placeholder: "Email", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :oscar, placeholder: "Oscar (Yes/No)", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :category, placeholder: "Category", class:"form-control" %>
                        </div>  
                        <div class="field">
                            <%= f.text_field :stars, placeholder: "Stars", class:"form-control" %>
                        </div> 
                        <div class="field">
                           <%= f.select :country, options_for_country, :prompt => 'Seleccionar el Pais', class:'form-control' %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :year, placeholder: "Año", class:"form-control" %>
                        </div>    
                        <div class="field">
                            <%= f.text_field :revenue_amount, placeholder: "Recaudacion", class:"form-control" %>
                        </div> 
                         <div class="field">
                            
                            <%= f.select :genre, options_for_genre, :prompt => 'Seleccionar el Genero', class:'form-control' %>
                        </div> 
                         <div class="field">
                            <%= f.text_field :precio, placeholder: "Precio", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :url, placeholder: "URL Imagen", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.text_field :movie_main, placeholder: "Video Principal Cabecera Sintaxis Link = https://www.youtube.com/embed/LINK_YOUTUBE", class:"form-control" %>
                        </div> 
                        <div class="field">
                            <%= f.submit "Guardar", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
                        </div>
                    <%end%>
                    <%= link_to 'Listado de Peliculas', @pelicula, class:"btn btn-sm btn-primary nodecor", style:"margin-top: 15px;" %> 
                    <br></br> 
                    <ol>
                        <li>El nombre no puede estar vacio.</li>
                        <li>No permite guardar 2 nombres en la BD con el mismo nombre.</li>
                        <li>La calificacion stars solo puede ser un rango 0 a 10.</li>
                        <li>El año ha de ser numerico.</li>
                        <li>La URL de la imagen no puede estar vacia.</li>
                        <li>El genero no puede estar vacio.</li>
                    </ol>  
            </div> <!-- end box -->
            <div class="row">
                <div class="margin20">
                    <%= @pelicula.errors.full_messages.each do |message| %>
                        <div class="message be-red white top-space text-center">
                            * <%= message %>
                        </div>
                    <%end%>
                </div> <!-- margin20 -->        
            </div> <!-- end row -->
            <!-- PARCIAL FOOTER --> 
            <%= render "shared/footer" %>
        </div> <!-- end controladorej2 -->
    </div> <!-- end container -->
</div> <!-- end estilosapp2 -->

app/views/peliculas/show.html.erb
<style>
.description {height:100%;margin:2%;} 
.descript-main {height: 182px;}
.score {height:80px;text-align:right;}
.fecha {display:none;}
img {width:150px;height:160px;}
.mas {display:none;}
.center-block {
   margin-left:auto;
   margin-right:auto;
   display:block;
} 
.status {
    font-family: 'Source Sans Pro', sans-serif;
}
.status .panel-title {
  font-family: 'Oswald', sans-serif;
  font-size: 32px;
  font-weight: bold;
  color: #fff;
  line-height: 40px;
  padding-top: 10px;
  letter-spacing: -0.8px;
}
.social-gradient {
  border-radius: 5px;  
  background: #67B26F;  
  background: -webkit-linear-gradient(to right, #4ca2cd, #67B26F);   
  background: linear-gradient(to right, #4ca2cd, #67B26F);  
}
.imgcartel {width: 100%; height: 520px;}
.opacidad:hover {opacity: 0.7;}
#social-margin {margin-left: 28% !important;}
/* SMARTHPHONE */
@media (max-width: 580px) { 
  .fblack_title {font-size:20px;}
  .box_show_comment {padding: 40px !important;}
}  
/* TABLET */
@media (max-width: 991px) {
  #social-margin {margin-left: 17% !important;}
} 
</style>
<div class="estilosapp2">
  <!-- PARCIAL HEADER --> 
  <%= render "shared/header" %>
  <div class="container"> 
    <div class="controladorej2"> 
      <div class="box_show"> 
        <div class="row">

          <div class="row marginleftright" style="margin-top: -1px;">
            <iframe  src="<%= @pelicula.movie_main %>" frameborder="0" allowfullscreen="allowfullscreen" style="width:100%;height:360px;margin-top:10px;"></iframe>
          </div><!-- end row -->    

          <div class="row fblack_title marginleftright" style="margin-top:-4px !important;">

            <div class="col-sm-8">  
              <div>&nbsp;<%= @pelicula.name %></div>
            </div><!-- end col-sm-8 -->   

            <div class="col-sm-4">  

              <div class="row">  
                <span class="size20" style="float:right;"><%= @pelicula.stars %>&nbsp;Stars&nbsp;&nbsp;</span>
              </div><!-- end row -->   

              <div class="row margintop10">    
                <%$i=0%>
                <%while $i < @pelicula.stars do%>
                  <span class="fa fa-star blue size18 opacidad" title="<%= @pelicula.stars %>" style="text-shadow:1px 2px 3px grey; float:right;"></span>
                  <% $i+=1 %>
                <%end%>
              </div><!-- end row -->  

            </div><!-- end col-sm-4 -->      
          </div><!-- end row -->   

           <!-- CONTENT -->
           <div class="row pad10">    
            <div style="margin-top:10px; height: 450px !important;"> 
              <div class="col-sm-4 col-md-4 col-xs-12">
                <img src="<%= @pelicula.url%>" class="img-responsive imgcartel opacidad" style="padding: 1%;"/><br/>
                <script language="javascript" src="http://www.elseptimoarte.net/recursos/cartelera/estrenos_1.php"></script>
              </div>
              <div class="col-sm-8 col-md-8 col-xs-12">

                <div class="description">   

                  <div class="row"> 
                    <h2>Descripción</h2>
                    <hr>
                    <h4><%= @pelicula.name%> es una pelicula realizada en <%= @pelicula.country%> de <%= @pelicula.genre.capitalize%> del año <%= @pelicula.year%> y dirigida por <%= @pelicula.director%> y protagonizada por <%= @pelicula.actor%>.</h4>    
                    <% $nombre=@pelicula.name%>
                    <%= link_to 'Wikipedia', "https://es.wikipedia.org/wiki/"+$nombre, target: "_blank", class:"btn btn-primary btn-xs nodecor " %>
                    <br></br>
                  </div><!-- end row -->

                  <div class="row">
                    <div class="col-sm-6">
                      <span class="bold">Actor Principal:</span>&nbsp;&nbsp;<%= @pelicula.actor%><br />
                      <span class="bold">Pais:</span>&nbsp;&nbsp;<%= @pelicula.country%><br />
                      <span class="bold">Email:</span>&nbsp;&nbsp;<%= @pelicula.email_contact%><br />
                      <span class="bold">Oscar:</span>&nbsp;&nbsp;<%= @pelicula.oscar%><br />
                      <span class="bold">Año:</span>&nbsp;&nbsp;<%= @pelicula.year%><br />
                    </div><!-- end col-sm-6 -->
                    <div class="col-sm-6">
                      <span class="bold">Ingresos obtenidos:</span>&nbsp;&nbsp;<%= @pelicula.revenue_amount%> $<br />
                      <span class="bold">Genero:</span>&nbsp;&nbsp;<%= @pelicula.genre.capitalize%><br />
                    </div><!-- end col-sm-6 -->
                  </div><!-- end row --> 

                  <div class="row">
                    <div class="col-sm-11" style="margin-left: 2%;">
                      <div class="offer offer-radius offer-primary">
                          <div class="shape">
                            <div class="shape-text">Film</div>
                          </div>
                          <div class="offer-content">
                            <h3 class="lead bold"><%= @pelicula.name %></h3>    
                            <div class="col-sm-6">       
                              <p class="lead">Last Offer is ...</p>
                            </div> <!-- col-sm-6 -->
                            <div class="col-sm-6">       
                              <div class="panel status panel-danger">
                                <div class="panel-heading">
                                  <h1 class="panel-title text-center"><%= @pelicula.precio/100.0 %>E</h1>
                                </div>
                                <div class="panel-body text-center">                        
                                  <strong>Last Price!!</strong>
                                </div>
                              </div><!-- panel status -->            
                            </div><!-- col-sm-6 -->   
                          </div><!-- offer-content -->            
                      </div><!-- offer -->            
                    </div><!-- end col-sm-11 -->   
                  </div><!-- end row --> 

                    <!-- VARIABLES SOCIAL BUTTONS -->
                    <% $face='https://www.facebook.com/sharer/sharer.php?u=http%3A//moviestoday.herokuapp.com/peliculas/'+@pelicula.id.to_s %>
                    <% $pinterest="https://pinterest.com/pin/create/button/?url=&media=http%3A//moviestoday.herokuapp.com/peliculas/"+@pelicula.id.to_s+"&description=MoviesToday Film "+@pelicula.name %>
                    <% $twitter="https://twitter.com/home?status=http%3A//moviestoday.herokuapp.com/peliculas/"+@pelicula.id.to_s %>
                    <% $google="https://plus.google.com/share?url=http%3A//moviestoday.herokuapp.com/peliculas/"+@pelicula.id.to_s %>
                    <% $linkedin="https://www.linkedin.com/shareArticle?mini=true&url=http%3A//moviestoday.herokuapp.com/peliculas/"+@pelicula.id.to_s+"&title="+@pelicula.name+"&summary=MoviesToday%20web%20dedicada%20los%20filmaniacos&source=" %>

                    <div class="row">  
                      <div class="col-sm-12">
                        <div class="social-gradient" style="height:110px;margin-top:12px;">
                          <h3 class="label label-default">SOCIAL SHARE</h3><br></br>
                            <ul id="social-margin" class="social-network social-circle social-network-margin" style="">
                              <li><a href="<%= $pinterest %>" class="icoRss" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
                              <li><a href="<%= $face %>" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                              <li><a href="<%= $twitter %>" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                              <li><a href="<%= $google %>" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                              <li><a href="<%= $linkedin %>" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>       
                        </div>  <!-- social-network -->
                      </div><!-- end col-sm-12 -->           
                    </div><!-- end row -->   

                </div><!--end description -->
              </div> <!-- end col-sm-8 -->  
            </div> <!-- end fwhitesmoke -->  
          </div><!-- end row -->  

          <div class="row">
            <div class="col-sm-12">
              <%= link_to 'Back to List', peliculas_path, class:"btn btn-sm btn-primary pull-right nodecor", style:"margin-right: 15px !important;" %>
            </div>
          </div> <!-- end row -->


          <!-- BOX_SHOW_COMMENT -->
          <div class="row">  
            <div class="box_show_comment">  
              <br>
              <h2>Comentarios</h2>
              <!-- PARCIAL COMENTARIOS -->
              <%= render @pelicula.comentarios %>
              <div class="panel panel-default panelmod1" style=" box-shadow: 1px 2px 3px gray;"> 
                <span style="font-size: 2em; margin-left:-7px;margin-bottom: 10px;">Añadir comentarios</span>
                </br>
                <!-- PARCIAL FORM COMENTARIOS -->
                <%= render "comentarios/form" %>
                <br></br>
              </div> <!-- end panel -->
              <div class="margin20">  
                <br>
                <%= @pelicula.errors.full_messages.each do |message| %>
                  <div class="be-red white top-space text-center">
                    * <%= message %>
                  </div>
                <%end%>
              </div> <!-- end margin20 -->
            </div> <!-- end box_show_comment -->
          </div> <!-- end row -->  

        </div> <!-- end box_show -->
      </div> <!-- end row -->
    </div> <!-- end controladorej2 -->
  </div> <!-- end container -->
</div> <!-- end estilosapp2 -->
<!-- PARCIAL FOOTER --> 
<%= render "shared/footer" %>