config/routes.rb
Rails.application.routes.draw do
   

  get 'payments/index'

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  #before sidekiq
  #devise_for :users
  # sidekiq
  devise_for :users, controllers: { registrations: "users/registrations"}
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  
  #root :to => "statics#index"
  #Example of regular route:
  #get 'about' => 'pages#about', as: 'about'
  #get '/about' => 'statics#about', :as => :about
  get 'about' => 'about#index', as: 'about'
  get 'settings/index'
  #get 'movies/index_search' => 'movies#index_search'
  #Example resource route
  resources :peliculas do
    resources :comentarios 
  end
  
  resources :settings
  resources :charges
  resources :select_movies, only: :index
  resources :payments, only: :index
  #root 'peliculas#index', as: 'home'
  #added for method root_path (search)
  root :to => "statics#index"

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
before_action :authenticate_user!
  def index
  end
  def new
    @user = User.find(params[:user])
    @@user = @user
    @amount = 500
    @@amount = @amount
    @@pelicula = ""
    @pelicula = ""
    @@subscript = ""
    @tipoplan = ""
    if params[:amount]
      @amount = params[:amount]
      @@amount = @amount
      @@pelicula = params[:pelicula]
      @pelicula=@@pelicula
    elsif params[:plan] == "bronze"
      @amount = 999
      @@amount = @amount
      @@subscript = :plan
      @tipoplan = "Bronze"
    elsif params[:plan] == "silver"
      @amount = 1299
      @@amount = @amount
      @@subscript = :plan
      @tipoplan = "Silver"
    elsif params[:plan] == "gold"
      @amount = 1999
      @@amount = @amount
      @@subscript = params[:plan]
      @tipoplan = "Gold"
    end
  end
  def create
    # Amount in cents
    @amount = @@amount
    @user = @@user
    @subscript = @@subscript
    @pelicula = @@pelicula
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'eur'
    )
    #current_user.payments.create(subscription: false, channel: "stripe", active: true, plan: 5, amount: 5)
    @payment = Payment.new
    @payment.user_id = current_user.id
    @payment.active = true
    if @subscript == "bronze" || @subscript == "silver" || @subscript == "gold"
      @payment.channel = "Stripe Subscript ( plan "+@subscript+" )"
      @payment.subscription = true
      @payment.plan = true
      @payment.amount = @amount
      @payment.save
    else
      @payment.channel = "Stripe Pay Film Title: "+@pelicula
      @payment.subscription = false
      @payment.plan = false
      @payment.amount = @amount
      @payment.save
    end  
    redirect_to settings_path
    rescue Stripe::CardError => e
      #flash[:error] = e.message
      redirect_to new_charge_path
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<style>
  .boxpay {
    background:#fff;
    margin-top: 10%;
    margin: 0 auto;
    transition:all 0.2s ease;
    border:2px dashed #dadada;
    width: 350px;
    margin-top: 10px;
    box-sizing: border-box;
    border-radius: 5px;
    background-clip: padding-box;
    padding:0 20px 20px 20px;
    min-height:390px;
  }
  .boxpay:hover {
    border:2px solid #525C7A; 
    background-image: linear-gradient(white, whitesmoke)
  }
  .boxpay span.box-title {
      color: #fff;
      font-size: 24px;
      font-weight: 300;
      text-transform: uppercase;
  }
  .boxpay .box-content {
    padding: 16px;
    border-radius: 0 0 2px 2px;
    background-clip: padding-box;
    box-sizing: border-box;
  }
  .boxpay .box-content p {
    color:#515c66;
    text-transform:none;
  }
  .botonmarge {margin-left: 25% !important;}
  .colteal {color:teal; font-weight: bold;}
  .colblue {color:blue; font-weight: bold;}
  .back {float:right; margin-top: 10px; margin-bottom:10px !important; padding:6px; background-color: teal; color:white;border-radius: 5px;text-decoration:none;}
</style>
<div class="container">
  <div class="row">
    <div class="col-md-2 text-center">
      <% if flash[:error].present? %>
        <div>
          <p><%= flash[:error] %></p>
        </div>
      <%end%>
      <%= form_tag charges_path do %>
        <div class="boxpay">
          <div class="box-content">
            <% if !@tipoplan.blank? %>
              <h1 class="tag-title">Plan <%= @tipoplan %></h1>
              <small>Payment subscription monthly</small>
              <hr/>
              <p>Subscripcion mensual al <span class="colblue">Plan <%= @tipoplan %></span> el pago se realiza mediante tarjeta de credito. Introduzca los datos de su tarjeta de credito y estara subscripto a nuestro plan mensual <span class="colteal"><%= @tipoplan %></span> y tambien a la subscripcion de nuestra revista mensual de forma gratuita.</p>
            <%else%>
              <h1 class="tag-title"><%= @pelicula %></h1>
              <small>Payment film</small>
              <hr/>
              <p>Ha escogido la pelicula <span class="colblue"><%= @pelicula %></span> el pago se realiza mediante tarjeta de credito. Introduzca los datos de su tarjeta de credito y se le enviara a su domicilio el producto que haya escogido. Si lo desea tambien puede subscribirse a uno de nuestros planes de subscripcion con varios descuentos.</p>  
            <%end%>
            <h3 class="text-center">Precio: <%= @amount.to_f/100.0 %> Euros</h3>
            <div class="botonmarge">
              <script
                  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-amount="<%= @amount %>"
                  data-name="Payment"
                  data-description="test"
                  data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                  data-locale="auto"
                  data-zip-code="true"
                  data-currency="eur">
              </script>                      
            </div> <!-- end botonmarge --> 
            <%= link_to 'Back', select_movies_path, class: "back", title:"Return to Select Movies" %><br/>
          </div> <!-- box-content -->
        </div> <!-- box-pay -->
      <%end%>
    </div> <!-- col-md-2 --> 
  </div> <!-- end row -->           
</div> <!-- end container -->